#!/bin/sh
### BEGIN INIT INFO
# Provides:          opsmxagent
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       opsmx tcollector
###  END INIT INFO

#Follow standards https://wiki.debian.org/LSBInitScripts

red=$(tput setaf 1)
green=$(tput setaf 2)
normal=$(tput sgr0)
blink=$(tput blink)
yellow=$(tput setaf 3)

SCRIPT="python /opt/tcollector/tcollector.py -D"
NAME="tcollector"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"

start() {
  if [ -f "$PIDFILE" ] && (ps -p $(cat "$PIDFILE") > /dev/null 2>&1);
  then
     echo ${yellow}'Tcollector(OpsMx) already running'${normal} >&2
     return 1
  fi
  sudo sh -c "$SCRIPT"
  if [ $? != "0" ];then
    echo ${red}'Tcollector(OpsMx) is not started'${normal} >&2
	exit 1
  fi
  echo ${green}'Tcollector(OpsMx) started'${normal} >&2
}

stop() {
  if [ -f "$PIDFILE" ] && (ps -p $(cat "$PIDFILE") > /dev/null 2>&1);
  then
    kill -0 $(cat "$PIDFILE") 2> /dev/null
    sudo kill -15 $(cat "$PIDFILE") && sudo rm -f "$PIDFILE"
    echo ${red}'Tcollector(OpsMx) stopped'${normal} >&2
  else
    echo ${red}'Tcollector(OpsMx) is not running'${normal} >&2
    return 1
  fi
}

status() {
  if [ -f "$PIDFILE" ] && (ps -p $(cat "$PIDFILE") > /dev/null 2>&1);
  then
    echo ${green}'Tcollector(OpsMx) is running'${normal} >&2
  else
    echo ${red}'Tcollector(OpsMx) is not running'${normal} >&2
  fi
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this OpsMx tcollector? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "NOTE: log file is not to be removed: '$LOGFILE'" >&2
    update-rc.d -f $NAME remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|uninstall}"
esac
